-- 265_sources_industry_group_ownership.sql
-- 目的：sources.industry 现有大量自由写法（live 全量普查 2026-09-18：1,607 行里 433 个非空写法，
-- 另 154 行为 NULL；enabled=true 的 1,392 行里 142 行没打标签），导致「按行业看校招覆盖」
-- 「校招专区按行业筛公司」都算不准（普查见 campus-census.md 第 2 节；该报告写的「144 个不同
-- industry 值 / 140 个 enabled 源无标签」与本次全量重新核实的数字有出入，以本次全量分页结果为准）。
--
-- 方案：新增 industry_group / ownership 两个归一列，**不改动原 industry / segment 列**（可回滚、
-- 不破坏现有读取方）。映射表来源是 lib/industry-taxonomy.json（433 条全量人工审定，逐条可查；
-- crawler/industry_taxonomy.py 与 lib/industry-taxonomy.ts 两端共读同一份 JSON，一致性由
-- tests/industry-taxonomy-cross-lang.test.js 全量对拍守住）。
--
-- industry_group 取值 = lib/company-industry.js 的 INDUSTRY_CATEGORIES / lib/must-apply-list.json
-- 的行业键（11 个）+ 'other'。⚠️ 注意是 11 个不是 10 个——must-apply-list.json 实测有
-- 互联网/科技、金融、消费/零售、制造/工业、汽车/出行、医疗/医药、能源/化工、地产/建筑、
-- 物流/供应链、传媒/文娱、教育 共 11 个行业键（tests/must-apply-list.test.js 已用
-- INDUSTRY_CATEGORIES 钉死这个数字），不新造第二套分类体系。
--
-- ownership 取值 = soe(央国企) / private(民企) / foreign(外企) / unknown。本迁移只回填「已有
-- 确凿依据」的行：sources.segment 已经是 soe/private/foreign 的直接照抄；segment 为 NULL 的记
-- unknown——**不使用「公司名含'中国'/'集团'/'国家'/'省' → 央国企」这类名称启发式**（这条在需求里
-- 只是建议，且本项目已有「京东 vs 京东方」这类子串张冠李戴的前车之鉴，未经验证不能拿来批量回填
-- 一个会被当筛选条件使用的字段）。lib/must-apply-list.json 逐家核实过：其 330 条公司记录里没有
-- 任何 segment/ownership 字段（只有 name/pattern/aliases/brandTokens/parentPattern），故此列
-- 也无法从必投清单反查，一并保持 unknown。

set local statement_timeout = '1800s';

-- 1) 新增列（幂等）
alter table sources add column if not exists industry_group text;
alter table sources add column if not exists ownership text;

-- 2) CHECK 约束（允许 NULL——NULL 表示"这行的 industry 本身就是空，从未打过标签"；
--    'other' 表示"industry 有值但不属于这 11 个行业"，两种语义不可混淆，见 crawler/industry_taxonomy.py 顶部注释）
alter table sources drop constraint if exists sources_industry_group_check;
alter table sources add constraint sources_industry_group_check
  check (industry_group is null or industry_group in (
    '互联网/科技',
    '金融',
    '消费/零售',
    '制造/工业',
    '汽车/出行',
    '医疗/医药',
    '能源/化工',
    '地产/建筑',
    '物流/供应链',
    '传媒/文娱',
    '教育',
    'other'
  ));

alter table sources drop constraint if exists sources_ownership_check;
alter table sources add constraint sources_ownership_check
  check (ownership is null or ownership in ('soe', 'private', 'foreign', 'unknown'));

-- 3) 索引：按行业/股权筛选是这次要支持的新查询场景（管理员看板「按行业看校招覆盖」、
--    校招专区按行业筛公司）
create index if not exists idx_sources_industry_group on sources(industry_group);
create index if not exists idx_sources_ownership on sources(ownership);

-- 4) 回填 industry_group：显式对照 lib/industry-taxonomy.json 的 mapping（433 条全量，
--    与该文件字节级一致，改分类只改那个 JSON 后重新生成本段，不要手改这里）。
--    industry 为 NULL 的行不进这条 update，industry_group 保持 NULL（不是 'other'）。
update sources
set industry_group = case industry
    when '3D打印' then '制造/工业'
    when 'ADC抗体药物偶联/创新药' then '医疗/医药'
    when 'AI' then '互联网/科技'
    when 'AI GPU芯片设计' then '制造/工业'
    when 'AIGC' then '互联网/科技'
    when 'AI·3D' then '互联网/科技'
    when 'AI·3D生成' then '互联网/科技'
    when 'AI·语音' then '互联网/科技'
    when 'AI医疗' then '医疗/医药'
    when 'AI大模型' then '互联网/科技'
    when 'AI应用' then '互联网/科技'
    when 'AI芯片' then '制造/工业'
    when 'AI芯片·具身智能' then '制造/工业'
    when 'AMR移动机器人/调度系统' then '制造/工业'
    when 'BI/数据分析SaaS' then '互联网/科技'
    when 'CXO' then '医疗/医药'
    when 'CXO/ADC偶联药物CDMO' then '医疗/医药'
    when 'CXO/新药研发外包' then '医疗/医药'
    when 'CXO/新药研发服务' then '医疗/医药'
    when 'EDA/良率分析工具' then '制造/工业'
    when 'EDA工具' then '制造/工业'
    when 'EDA软件' then '制造/工业'
    when 'FPGA芯片设计' then '制造/工业'
    when 'HR SaaS' then '互联网/科技'
    when 'ICT·通信设备' then '制造/工业'
    when 'IVD体外诊断' then '医疗/医药'
    when 'LED显示' then '制造/工业'
    when 'MCN' then '传媒/文娱'
    when 'MCN/营销' then '传媒/文娱'
    when 'MCU/模拟混合信号芯片' then '制造/工业'
    when 'RTC/实时音视频云' then '互联网/科技'
    when 'discover' then 'other'
    when '专用车/石油装备' then '汽车/出行'
    when '个护/洗护' then '消费/零售'
    when '中药' then '医疗/医药'
    when '主题公园/景区' then '传媒/文娱'
    when '乳业·消费' then '消费/零售'
    when '云计算' then '互联网/科技'
    when '互联网' then '互联网/科技'
    when '互联网/科技' then '互联网/科技'
    when '互联网·云' then '互联网/科技'
    when '互联网·内容' then '互联网/科技'
    when '互联网·内容社区' then '互联网/科技'
    when '互联网·出行' then '汽车/出行'
    when '互联网·媒体' then '传媒/文娱'
    when '互联网·安全' then '互联网/科技'
    when '互联网·智能物联' then '互联网/科技'
    when '互联网·智能终端' then '制造/工业'
    when '互联网·游戏' then '互联网/科技'
    when '互联网·电商' then '互联网/科技'
    when '互联网·社区电商' then '互联网/科技'
    when '互联网·通信' then '互联网/科技'
    when '互联网保险' then '金融'
    when '互联网券商' then '互联网/科技'
    when '互联网医疗' then '医疗/医药'
    when '互联网科技' then '互联网/科技'
    when '互联网金融' then '金融'
    when '五金电工·消费' then '制造/工业'
    when '人工智能' then '互联网/科技'
    when '人工智能/AI应用' then '互联网/科技'
    when '人工智能/机器视觉' then '制造/工业'
    when '人形机器人' then '制造/工业'
    when '企业IT' then '制造/工业'
    when '企业服务' then '互联网/科技'
    when '企业服务/SaaS' then '互联网/科技'
    when '企业软件' then '互联网/科技'
    when '企业软件/ERP实施' then '互联网/科技'
    when '企业软件/IT服务' then '制造/工业'
    when '休闲零食' then '消费/零售'
    when '休闲零食/小鱼仔' then '消费/零售'
    when '传媒/文娱' then '传媒/文娱'
    when '伴随诊断/肿瘤基因检测' then '医疗/医药'
    when '保险' then '金融'
    when '保险科技' then '金融'
    when '信创·服务器' then '互联网/科技'
    when '信息技术' then '互联网/科技'
    when '储能' then '制造/工业'
    when '储能·消费电子' then '制造/工业'
    when '储能电池' then '制造/工业'
    when '光伏' then '制造/工业'
    when '光伏·储能' then '制造/工业'
    when '光伏·农牧' then '制造/工业'
    when '光伏·新能源' then '制造/工业'
    when '光伏微逆变器' then '制造/工业'
    when '光伏组件' then '制造/工业'
    when '光伏逆变器' then '制造/工业'
    when '光刻设备' then '制造/工业'
    when '光学' then '制造/工业'
    when '光通信' then '制造/工业'
    when '公募基金' then '金融'
    when '具身智能' then '制造/工业'
    when '养殖' then '消费/零售'
    when '内容平台' then '互联网/科技'
    when '军工·央企' then '制造/工业'
    when '农业/食品/养殖' then '消费/零售'
    when '农牧饲料/养殖' then '消费/零售'
    when '出海广告/移动营销' then '传媒/文娱'
    when '出行' then '汽车/出行'
    when '创投' then '金融'
    when '创新药' then '医疗/医药'
    when '创新药/肝病肿瘤' then '医疗/医药'
    when '创新药/许可引进' then '医疗/医药'
    when '制造/工业' then '制造/工业'
    when '制造·注塑机' then '制造/工业'
    when '动力/储能电池' then '制造/工业'
    when '动力电池' then '制造/工业'
    when '化工' then '能源/化工'
    when '化工·央企' then '能源/化工'
    when '化工·气体' then '能源/化工'
    when '医检' then '医疗/医药'
    when '医疗' then '医疗/医药'
    when '医疗/医药' then '医疗/医药'
    when '医疗AI' then '医疗/医药'
    when '医疗·健康科技' then '医疗/医药'
    when '医疗健康' then '医疗/医药'
    when '医疗器械' then '医疗/医药'
    when '医疗器械·影像设备' then '医疗/医药'
    when '医疗大数据' then '医疗/医药'
    when '医疗影像' then '医疗/医药'
    when '医疗服务' then '医疗/医药'
    when '医疗设备' then '医疗/医药'
    when '医药' then '医疗/医药'
    when '医药·CRO' then '医疗/医药'
    when '医药·医疗' then '医疗/医药'
    when '医药·生物' then '医疗/医药'
    when '医药健康' then '医疗/医药'
    when '医药制造' then '医疗/医药'
    when '医药制造/麻醉生殖' then '医疗/医药'
    when '医药医疗' then '医疗/医药'
    when '医药商业流通/批发分销' then '医疗/医药'
    when '医药外包' then '医疗/医药'
    when '医药流通/疫苗' then '医疗/医药'
    when '半导体' then '制造/工业'
    when '半导体·射频' then '制造/工业'
    when '半导体材料' then '制造/工业'
    when '半导体设备' then '制造/工业'
    when '协同办公' then '互联网/科技'
    when '口腔' then '医疗/医药'
    when '口腔护理' then '医疗/医药'
    when '商业地产' then '地产/建筑'
    when '啤酒' then '消费/零售'
    when '四足机器人/人形机器人' then '制造/工业'
    when '在线旅游' then '互联网/科技'
    when '在线票务' then '传媒/文娱'
    when '在线视频' then '互联网/科技'
    when '地产' then '地产/建筑'
    when '地产/住宅开发' then '地产/建筑'
    when '地产/建筑' then '地产/建筑'
    when '地图出行' then '汽车/出行'
    when '城商行' then '金融'
    when '基因' then '医疗/医药'
    when '基金' then '金融'
    when '基金·资管' then '金融'
    when '大宗商品供应链' then '物流/供应链'
    when '大数据/数据库' then '互联网/科技'
    when '媒体平台' then '传媒/文娱'
    when '存储芯片' then '制造/工业'
    when '存储芯片/DRAM' then '制造/工业'
    when '安全 SaaS' then '互联网/科技'
    when '安防' then '互联网/科技'
    when '安防·AIoT' then '互联网/科技'
    when '定制家居/建材' then '制造/工业'
    when '定制家居/软件' then '消费/零售'
    when '家居家纺' then '消费/零售'
    when '家居建材零售' then '制造/工业'
    when '家电' then '制造/工业'
    when '导航定位' then '制造/工业'
    when '嵌入式/多媒体芯片设计' then '制造/工业'
    when '工业/燃气分销' then '能源/化工'
    when '工业/雾化科技' then '制造/工业'
    when '工业·暖通' then '制造/工业'
    when '工业·楼宇' then '制造/工业'
    when '工业·电梯' then '制造/工业'
    when '工业·航空' then '制造/工业'
    when '工业互联网/3D视觉/传感器' then '制造/工业'
    when '工业机器人' then '制造/工业'
    when '工业自动化' then '制造/工业'
    when '工业自动化/DCS/PLC' then '制造/工业'
    when '工业自动化/变频器' then '制造/工业'
    when '工业自动化/工业视觉' then '制造/工业'
    when '工业软件' then '制造/工业'
    when '工业软件/CAD/CAE' then '制造/工业'
    when '工业软件/CAPP/PDM/PLM' then '制造/工业'
    when '工业驱动/伺服系统' then '制造/工业'
    when '工程机械' then '制造/工业'
    when '建材' then '制造/工业'
    when '建材/工业材料' then '制造/工业'
    when '建筑/工业涂料' then '地产/建筑'
    when '建筑地产' then '地产/建筑'
    when '建筑工程·央企' then '地产/建筑'
    when '建筑软件' then '地产/建筑'
    when '彩票科技' then '传媒/文娱'
    when '快消零售' then '消费/零售'
    when '房产经纪/居住服务' then '地产/建筑'
    when '房地产' then '地产/建筑'
    when '房地产开发' then '地产/建筑'
    when '手机/智能终端' then '制造/工业'
    when '摩托车' then '汽车/出行'
    when '支付' then '金融'
    when '教育' then '教育'
    when '教育·AI' then '教育'
    when '教育大数据' then '教育'
    when '教育科技' then '教育'
    when '数字银行/金融科技' then '金融'
    when '数字阅读/网络文学' then '互联网/科技'
    when '文具' then '消费/零售'
    when '文娱' then '传媒/文娱'
    when '新材料' then '制造/工业'
    when '新消费' then '消费/零售'
    when '新能源' then '能源/化工'
    when '新能源·电池' then '制造/工业'
    when '新能源·风电' then '制造/工业'
    when '新能源汽车/制造' then '汽车/出行'
    when '新能源连接器' then '能源/化工'
    when '新茶饮' then '消费/零售'
    when '方便食品' then '消费/零售'
    when '方便食品/饮料' then '消费/零售'
    when '旅游' then '消费/零售'
    when '无人机' then '制造/工业'
    when '无人机·智能硬件' then '制造/工业'
    when '日化' then '消费/零售'
    when '日化/个护' then '消费/零售'
    when '日用品' then '消费/零售'
    when '时尚男装' then '消费/零售'
    when '显示面板' then '制造/工业'
    when '显示面板·半导体' then '制造/工业'
    when '智能制造' then '制造/工业'
    when '智能座舱' then '汽车/出行'
    when '智能影像' then '制造/工业'
    when '智能硬件' then '制造/工业'
    when '智能硬件/可穿戴' then '制造/工业'
    when '智能装备' then '制造/工业'
    when '智能财税' then '互联网/科技'
    when '智能驾驶' then '汽车/出行'
    when '智能驾驶/ADAS' then '汽车/出行'
    when '智能驾驶/自动驾驶' then '汽车/出行'
    when '有色金属' then '能源/化工'
    when '服务机器人/配送机器人' then '制造/工业'
    when '服装' then '消费/零售'
    when '本地生活' then '互联网/科技'
    when '本地生活/互联网' then '互联网/科技'
    when '机器人' then '制造/工业'
    when '机器视觉' then '制造/工业'
    when '材料·央企' then '制造/工业'
    when '核工业·能源' then '能源/化工'
    when '核能' then '能源/化工'
    when '检测设备' then '制造/工业'
    when '氟化工/氯碱' then '能源/化工'
    when '水泥' then '制造/工业'
    when '汽车' then '汽车/出行'
    when '汽车/出行' then '汽车/出行'
    when '汽车·内容' then '汽车/出行'
    when '汽车·制造' then '汽车/出行'
    when '汽车·新能源' then '汽车/出行'
    when '汽车·智能电动' then '汽车/出行'
    when '汽车互联网/电商' then '汽车/出行'
    when '汽车制造' then '汽车/出行'
    when '汽车后市场/数字化' then '汽车/出行'
    when '汽车整车/合资' then '汽车/出行'
    when '汽车整车/新能源汽车' then '汽车/出行'
    when '汽车电子/TPMS' then '汽车/出行'
    when '汽车零部件' then '汽车/出行'
    when '汽车零部件/内饰' then '汽车/出行'
    when '法务/电子合同 SaaS' then '互联网/科技'
    when '涂料/建筑涂料' then '地产/建筑'
    when '消费' then '消费/零售'
    when '消费/零售' then '消费/零售'
    when '消费/零食饮料' then '消费/零售'
    when '消费·服饰' then '消费/零售'
    when '消费·纺织' then '消费/零售'
    when '消费·运动' then '消费/零售'
    when '消费·运动服饰' then '消费/零售'
    when '消费·运动零售' then '消费/零售'
    when '消费·酒类' then '消费/零售'
    when '消费·零食' then '消费/零售'
    when '消费·食品' then '消费/零售'
    when '消费·饮料' then '消费/零售'
    when '消费健康' then '消费/零售'
    when '消费电子' then '制造/工业'
    when '消费电子/PC' then '制造/工业'
    when '消费电子·手机' then '制造/工业'
    when '消费电子·教育电子' then '制造/工业'
    when '消费电子·显示' then '制造/工业'
    when '消费金融' then '金融'
    when '消费金融/金融科技' then '金融'
    when '消费零售' then '消费/零售'
    when '游戏' then '互联网/科技'
    when '游戏/互联网' then '互联网/科技'
    when '游戏·元宇宙' then '互联网/科技'
    when '游戏发行' then '互联网/科技'
    when '潮玩' then '消费/零售'
    when '潮玩谷子/IP衍生-日系手办/周边' then '消费/零售'
    when '激光' then '制造/工业'
    when '激光设备' then '制造/工业'
    when '激光雷达' then '汽车/出行'
    when '激光雷达/ToF传感器' then '汽车/出行'
    when '热管理/冷却系统' then '制造/工业'
    when '热管理/车载电源' then '制造/工业'
    when '照明' then '制造/工业'
    when '物业服务' then '地产/建筑'
    when '物业管理/代建' then '地产/建筑'
    when '物流' then '物流/供应链'
    when '物流/供应链' then '物流/供应链'
    when '物流·央企' then '物流/供应链'
    when '物流·航运' then '物流/供应链'
    when '物流末端' then '物流/供应链'
    when '物流机器人' then '物流/供应链'
    when '物流科技' then '物流/供应链'
    when '物联网' then '互联网/科技'
    when '物联网模组' then '互联网/科技'
    when '环境检测/第三方检测' then '制造/工业'
    when '珠三角·注塑机/压铸机' then '制造/工业'
    when '珠宝' then '消费/零售'
    when '生命科学' then '医疗/医药'
    when '生命科学·诊断' then '医疗/医药'
    when '生命科学工具/分子诊断' then '医疗/医药'
    when '生活服务' then '互联网/科技'
    when '生物制品' then '医疗/医药'
    when '生物制药' then '医疗/医药'
    when '生物医药' then '医疗/医药'
    when '生物类似药/单克隆抗体' then '医疗/医药'
    when '电信IT/数字化' then '制造/工业'
    when '电信·央企' then '互联网/科技'
    when '电信设备' then '制造/工业'
    when '电力' then '能源/化工'
    when '电动车' then '汽车/出行'
    when '电商' then '互联网/科技'
    when '电商/互联网' then '互联网/科技'
    when '电商/生活服务' then '互联网/科技'
    when '电子制造' then '制造/工业'
    when '电子测量' then '制造/工业'
    when '电工' then '制造/工业'
    when '电气' then '制造/工业'
    when '电气/液压' then '制造/工业'
    when '电池' then '制造/工业'
    when '男装/休闲服装' then '消费/零售'
    when '直播' then '互联网/科技'
    when '直播·社交' then '互联网/科技'
    when '眼科·医疗' then '医疗/医药'
    when '知名私企' then 'other'
    when '短视频/互联网' then '互联网/科技'
    when '石化/特种材料' then '能源/化工'
    when '矿业' then '能源/化工'
    when '矿业-金矿/铜矿' then '能源/化工'
    when '研发管理 SaaS' then '互联网/科技'
    when '硬件·IT' then '制造/工业'
    when '科技' then '互联网/科技'
    when '科技·军工' then '制造/工业'
    when '粮油' then '消费/零售'
    when '精密制造' then '制造/工业'
    when '线控底盘/转向系统' then '汽车/出行'
    when '综合' then 'other'
    when '综合·地产·国资' then '地产/建筑'
    when '综合·央企' then 'other'
    when '综合·实业·国资' then 'other'
    when '综合证券' then '金融'
    when '网络安全' then '互联网/科技'
    when '网络安全/威胁情报' then '互联网/科技'
    when '网络设备' then '制造/工业'
    when '美妆' then '消费/零售'
    when '美妆个护' then '消费/零售'
    when '职业培训' then '教育'
    when '肉类食品加工' then '消费/零售'
    when '能源' then '能源/化工'
    when '能源/化工' then '能源/化工'
    when '能源·核电·央企' then '能源/化工'
    when '能源电力' then '能源/化工'
    when '膜材料' then '制造/工业'
    when '自动驾驶' then '汽车/出行'
    when '船舶/海洋工程' then '制造/工业'
    when '芳纶/高性能纤维' then '制造/工业'
    when '茶饮/茶叶零售' then '消费/零售'
    when '营销传播' then '传媒/文娱'
    when '血液/免疫肿瘤创新药' then '医疗/医药'
    when '装备' then '制造/工业'
    when '装备制造' then '制造/工业'
    when '装备重工' then '制造/工业'
    when '视频监控芯片' then '制造/工业'
    when '视频社区/互联网' then '互联网/科技'
    when '证券' then '金融'
    when '财税/能源管理 SaaS' then '互联网/科技'
    when '财税SaaS' then '互联网/科技'
    when '跨境电商' then '互联网/科技'
    when '跨境电商物流' then '物流/供应链'
    when '轨道交通' then '制造/工业'
    when '轨道交通装备/信号' then '制造/工业'
    when '轮胎/橡胶' then '制造/工业'
    when '软件' then '互联网/科技'
    when '软件·云' then '互联网/科技'
    when '输变电设备/电力变压器/HVDC' then '能源/化工'
    when '运动健身-家用健身器械' then '消费/零售'
    when '运动健身-精品健身工作室' then '消费/零售'
    when '运动控制/工业机器人' then '制造/工业'
    when '运动控制/工业自动化' then '制造/工业'
    when '运动服饰' then '消费/零售'
    when '连锁药店/零售药店' then '医疗/医药'
    when '通信' then '互联网/科技'
    when '通信·央企子公司' then '互联网/科技'
    when '通信·科技' then '互联网/科技'
    when '通信设备' then '制造/工业'
    when '通信设备/云计算' then '制造/工业'
    when '通信运营商' then '互联网/科技'
    when '酒店连锁' then '消费/零售'
    when '量化投资' then '金融'
    when '金融' then '金融'
    when '金融·保险' then '金融'
    when '金融·保险经纪' then '金融'
    when '金融·支付' then '金融'
    when '金融·资产管理' then '金融'
    when '金融·资管' then '金融'
    when '金融科技' then '金融'
    when '金融科技/互联网' then '金融'
    when '金融科技·券商' then '金融'
    when '钢铁' then '能源/化工'
    when '银行' then '金融'
    when '银行金融' then '金融'
    when '锂电' then '制造/工业'
    when '锂电正极材料' then '制造/工业'
    when '锂电装备' then '制造/工业'
    when '锂电负极材料' then '制造/工业'
    when '长视频/影视' then '传媒/文娱'
    when '零售' then '消费/零售'
    when '零售科技' then '消费/零售'
    when '音乐娱乐/互联网' then '传媒/文娱'
    when '音频平台' then '互联网/科技'
    when '预制菜/速冻食品' then '消费/零售'
    when '食品' then '消费/零售'
    when '食品·乳业' then '消费/零售'
    when '食品·饮料' then '消费/零售'
    when '食品饮料' then '消费/零售'
    when '餐饮' then '消费/零售'
    when '餐饮连锁/快餐' then '消费/零售'
    when '高端女装' then '消费/零售'
    else null
  end
where industry is not null;

-- 5) 映射不到的（industry 有值但不在上面的显式表里，理论上普查已覆盖全部 433 个非空值，
--    这里仅作未来新增写法的防御性兜底）→ 'other'，不许猜成某个具体行业。
update sources
set industry_group = 'other'
where industry is not null and industry_group is null;

-- 6) 回填 ownership：已有 segment 的照抄，NULL 的记 unknown（不做名称启发式，见上方方案说明）。
update sources
set ownership = case
    when segment in ('soe', 'private', 'foreign') then segment
    else 'unknown'
  end
where ownership is null;
